### PR TITLE
Make necessary changes to update to material-ui v5 RC

### PR DESCRIPTION
**Pull request by ShotSkydiver**
The just-released material-ui RC-0 includes the new package names that material-ui is transitioning to -- material-ui to mui. This PR updates the packages to that new version and makes the necessary renames in the code.

### CODE REVIEW

**Comment by henry-young** [comment]
Shout out to [@Mitch528](https://github.com/Mitch528) for publishing this branch to NPM until this PR is merged https://www.npmjs.com/package/@mitch528/mdi-material-ui

**Comment by JeremyGrieshop** [comment]
I've noticed that icons imported via `mdi-material-ui` using a `color` prop doesn't get the correct theme settings for MUI5.  Does fixing the imports in this PR get this correct, or do you think there's more to do there?

**Comment by stunaz** [comment]
@leMaik any change to release this for the compatibility of material-ui v5

**Comment by mkermani144** [comment]
This also fixes #43.

**Comment by leMaik** [comment]
@olee Sorry, this went below my radar. :sweat: 
@Philipp91 Thank you for jumping in! :tada: I'll release a new version shortly.

**Comment by leMaik** [comment]
@ShotSkydiver Thanks a lot for updating this :pray:

**Comment by JeremyGrieshop** [comment]
Awesome, thank you, my icon colors are back to normal now!

**Pull request merged**
